on:
  push:
    branches:
    - master
name: Create release
jobs:
  release:
    name: Create a new github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Autotag
        id: autotag
        uses: butlerlogic/action-autotag@1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          strategy: package
          tag_message: ${{ github.event.head_commit.message }}

      - name: Create Release
        if: steps.autotag.outputs.tagname != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@latest
        with:
          tag_name: ${{steps.autotag.outputs.tagname}}
          release_name: ${{steps.autotag.outputs.tagname}}
          body: ${{steps.autotag.outputs.tagmessage}}
          draft: false
          prerelease: false